version: '2'
services:
  web:
    build: .
    volumes:
      - "./:/tienda-dss"
    ports:
     - "3001:3001"
    command: "bin/rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - database_storedss
    links:
      - database_storedss:database_storedss
    stdin_open: true
  database_storedss:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB=tienda_dss
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
